BesikduzuSeyahat_BusTicket_Furkan_Kaya/BesikduzuSeyahat.WebUI/Controllers/TravelController.cs
using BesikduzuSeyahat.Business.Abstract;
using BesikduzuSeyahat.Entity;
using BesikduzuSeyahat.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BesikduzuSeyahat.WebUI.Controllers
{
    public class TravelController : Controller
    {
        private IDirectionService _directionService;
        private ITicketService _ticketService;

        public TravelController(IDirectionService directionService, ITicketService ticketService)
        {

            this._directionService = directionService;
            this._ticketService = ticketService;
        }

        public IActionResult Details(int id)
        {
            Direction direction = _directionService.GetDirectionDetails(id);
            int directionSeatNumber = _ticketService.GetCountBySeat(id);
            List<int> soldSeats = _ticketService.GetSeat(id);
            var seats = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40 };
            foreach (var item in soldSeats)
            {
                seats.Remove(item);
            }

            ViewBag.Number = directionSeatNumber;
            ViewBag.Seats = new SelectList(seats);

            if (direction == null)
            {
                return NotFound();
            }
            else
            {

                return View(direction);
            }
        }

        [HttpPost]
        public IActionResult Details(int directionId, double price, string departure, string arrival, int seatNo, string passengerMail, string passengerTel, string passengerName, string passengerSurname)
        {
            var entity = new Ticket()
            {
                PassengerName = passengerName,
                PassengerSurname = passengerSurname,
                PassengerMail = passengerMail,
                PassengerTel = passengerTel,
                Departure = departure,
                Arrival = arrival,
                SeatNo = seatNo,
                Price = price,
                DirectionId = directionId
            };
            _ticketService.Create(entity);
            return RedirectToAction("Succeed");
        }



        public IActionResult Succeed()
        {
            Ticket newTicket = _ticketService.GetLastSave();
            int directionId = _ticketService.GetId();
            string directionTime = _ticketService.GetTime(directionId);
            string directionDate = _ticketService.GetDate(directionId);

            var directionTicket = new DirectionTicket()
            {
                Date = directionDate,
                Time = directionTime,
                Ticket = newTicket
            };
            return View(directionTicket);
        }
    }
}

BesikduzuSeyahat_BusTicket_Furkan_Kaya/BesikduzuSeyahat.WebUI/Controllers/UserController.cs
using BesikduzuSeyahat.Business.Abstract;
using BesikduzuSeyahat.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BesikduzuSeyahat.WebUI.Controllers
{
    public class UserController : Controller
    {
        private ITicketService _ticketService;
        public UserController(ITicketService biletService)
        {
            this._ticketService = biletService;
        }
        public IActionResult AdminList()
        {
            return View(new DirectionTicket()
            {
                Tickets = _ticketService.GetAll()
            });
        }

        public IActionResult CancelTicket(int ticketId)
        {
            var ticket = _ticketService.GetById(ticketId);
            if (ticket != null)
            {
                _ticketService.Delete(ticket);
            }
            return RedirectToAction("AdminList");
        }
    }
}

BesikduzuSeyahat_BusTicket_Furkan_Kaya/BesikduzuSeyahat.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BesikduzuSeyahat.WebUI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <img src="/image/otobuslogo1.png" alt="">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Beşikdüzü Seyahat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="AdminList">Admin</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Güzergah
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="direction" asp-action="directionlist">Güzergah Listesi</a></li>
                                <li><a class="dropdown-item" asp-controller="direction" asp-action="createdirection">Güzergah Oluştur</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Kurumsal
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="History">Tarihçe</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="BoardMembers">Yönetim Kurulu</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Hizmetlerimiz
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="Treats">İkramlar</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="ServiceCenter">Dinlenme Tesisleri</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="altKısım container-sm">
            <a href="#"><img src="/image/facebook1.png" alt=""></a>
            <a href="#"><img src="/image/mail1.png" alt=""></a>
            <a href="#"><img src="/image/twitter1.png" alt=""></a>
            <a href="#"><img src="/image/youtube1.png" alt=""></a>
        </div>
        <p>Sosyal Medya Hesaplarımızı Takip Etmeyi Unutmayın. Copyright © 2022 Beşikdüzü Seyahat</p>
    </footer>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BesikduzuSeyahat_BusTicket_Furkan_Kaya/BesikduzuSeyahat.WebUI/Views/Shared/_noTravel.cshtml
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert danger" role="alert">
    <h6 class="text-warning">Lütfen uygun bir sefer seçiniz.</h6>
</div>
        <h6 class="display-4">Seferlerimiz</h6>
        <hr />
        <table class="table table-sm table-bordered">
            <thead>
                <tr>
                    <th>Kalkış</th>
                    <th>Ara Durak</th>
                    <th>Ara Durak</th>
                    <th>Ara Durak</th>
                    <th>Varış</th>
                </tr>
            </thead>
            <tbody>
                        <tr class="bg-primary">
                            <td>İstanbul</td>
                            <td>Kocaeli</td>
                            <td>Kütahya</td>
                            <td>Afyon</td>
                            <td>Isparta</td>
                        </tr>

                        <tr class="bg-secondary">
                            <td>Edirne</td>
                            <td>Sakarya</td>
                            <td>Bolu</td>
                            <td>Çorum</td>
                            <td>Giresun</td>
                        </tr>

                        <tr class="bg-info">
                            <td>Artvin</td>
                            <td>Trabzon</td>
                            <td>Ordu</td>
                            <td>Samsun</td>
                            <td>Ankara</td>
                        </tr>

                        <tr class="bg-primary">
                            <td>Isparta</td>
                            <td>Afyon</td>
                            <td>Kütahya</td>
                            <td>Kocaeli</td>
                            <td>İstanbul</td>
                        </tr>

                        <tr class="bg-secondary">
                            <td>Giresun</td>
                            <td>Çorum</td>
                            <td>Bolu</td>
                            <td>Sakarya</td>
                            <td>Edirne</td>
                        </tr>

                        <tr class="bg-info">
                            <td>Ankara</td>
                            <td>Samsun</td>
                            <td>Ordu</td>
                            <td>Trabzon</td>
                            <td>Artvin</td>
                        </tr>
            </tbody>
        </table>
        
        

BesikduzuSeyahat_BusTicket_Furkan_Kaya/BesikduzuSeyahat.WebUI/Views/Shared/travel.cshtml
@model Direction

<div class="card mb-4 mt-3 shadow">
    
    <div class="card-body">
        <a class="card-title" asp-controller="Travel" asp-action="Details" asp-route-id="@Model.DirectionId" style="text-decoration:none; font-size:24px;">@Model.Start <i class="fas fa-long-arrow-alt-right"></i> @Model.Finish</a>
        <p class="card-text"><b style="font-size:19px;">Güzergah:</b>  @Model.Start > @Model.direction1 > @Model.direction2 > @Model.direction3 > @Model.Finish</p><br />

        <p style=" font-size:24px; text-align:center;">
            <b>@Model.Date </b>
            - @Model.Time
        </p>

        
    </div>
    <div class="card-footer text-center">
        <a asp-controller="Travel" asp-action="Details" asp-route-id="@Model.DirectionId" class="btn btn-primary btn-sm">İncele</a>
        
    </div>
</div>   